// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCboxWjpjnFPrT9bfcc4iLetNxZDAr5Qzc',
    appId: '1:941095566314:web:74cf2078f52103a6d2d093',
    messagingSenderId: '941095566314',
    projectId: 'mpss-d477f',
    authDomain: 'mpss-d477f.firebaseapp.com',
    storageBucket: 'mpss-d477f.appspot.com',
    measurementId: 'G-E8EB4CKTSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvrSyuv1BUQkh5bXeCpC07siuAmGuP2mI',
    appId: '1:941095566314:android:fda52d9fdd240332d2d093',
    messagingSenderId: '941095566314',
    projectId: 'mpss-d477f',
    storageBucket: 'mpss-d477f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHiU8thwitS0nvLM9eGa3wPt_vniE4NI0',
    appId: '1:941095566314:ios:bf36b6dddbda55b4d2d093',
    messagingSenderId: '941095566314',
    projectId: 'mpss-d477f',
    storageBucket: 'mpss-d477f.appspot.com',
    androidClientId: '941095566314-8ittmf5vpgk0lhd81kaejd40f4kmd88a.apps.googleusercontent.com',
    iosClientId: '941095566314-4t74meukn20t84mmq6cn1rbk96fd9n30.apps.googleusercontent.com',
    iosBundleId: 'com.engoo.finalmps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHiU8thwitS0nvLM9eGa3wPt_vniE4NI0',
    appId: '1:941095566314:ios:972fe380d6464ac6d2d093',
    messagingSenderId: '941095566314',
    projectId: 'mpss-d477f',
    storageBucket: 'mpss-d477f.appspot.com',
    androidClientId: '941095566314-8ittmf5vpgk0lhd81kaejd40f4kmd88a.apps.googleusercontent.com',
    iosClientId: '941095566314-8v76jproepevt9mvb4480tqh27mu7omc.apps.googleusercontent.com',
    iosBundleId: 'com.engoo.finalMps',
  );
}
